### ISSUE TITLE
Consider not using ets for each connection

### ISSUE THREAD

**Issue by Gazler** [Aircloak/phoenix_gen_socket_client#17]
Currently, one ets table is used per connection. This means that if there are more than ~1400 connections, then the ets table limit will be hit.

The table is created at https://github.com/Aircloak/phoenix_gen_socket_client/blob/4fbddbf2b4f94e81131bf84ed2a6c31988f7fcac/lib/gen_socket_client.ex#L231

I have a quick fix at the moment using a named table (on this branch https://github.com/VoiceLayer/phoenix_gen_socket_client/tree/fix/ets-limit), however I am sure there are much better solutions we could implement.

**Comment by Gazler** [comment]
Just to add, the application that I used to discover this issue was https://github.com/VoiceLayer/channel_benchmarker

**Comment by sasa1977** [comment]
We should definitely remove the requirement of one ets table per client connection. However, there are some issues in your quick fix:

- potential race condition when creating table
- possible memory leak if the connection process crashes
- read/write concurrency should be set

Personally, I think that the easiest fix would be to use procdict instead of an ets table. That should allow us to keep the same API while removing the resource/memory pressure of ETS tables. Finally, procdict solution wouldn't suffer from the issues I mentioned above. Could you try that out and make a PR if it works?

Going further, we should consider if we can avoid implicit side-effects. I'm on a fence whether it's worth it, but either way, if we want to do that, we'll need to change the interface, so I think it deserves some more careful consideration.

**Comment by Gazler** [comment]
I wasn't suggesting my hack as an actual fix. I just wanted something
working whilst keeping ets incase there was a reason it was being used.

I agree with using the process dictionary. I'll take a shot at it and send
a PR


On 15 Jun 2017 20:58, "Saša Jurić" <notifications@github.com> wrote:

We should definitely remove the requirement of one ets table per client
connection. However, there are some issues in your quick fix:

   - potential race condition when creating table
   - possible memory leak if the connection process crashes
   - read/write concurrency should be set

Personally, I think that the easiest fix would be to use procdict instead
of an ets table. That should allow us to keep the same API while removing
the resource/memory pressure of ETS tables. Finally, procdict solution
wouldn't suffer from the issues I mentioned above. Could you try that out
and make a PR if it works?

Going further, we should consider if we can avoid implicit side-effects.
I'm on a fence whether it's worth it, but either way, if we want to do
that, we'll need to change the interface, so I think it deserves some more
careful consideration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Aircloak/phoenix_gen_socket_client/issues/17#issuecomment-308849747>,
or mute the thread
