### ISSUE TITLE
Listening to Phoenix Channel from Erlang Node

### ISSUE THREAD

**Issue by nitinjain1105** [Aircloak/phoenix_gen_socket_client#39]
Hi @aircloak 

I am trying to listen to phoenix channel from Erlang Node, I see that this library works when we are trying to listen from an Elixir Node.

Do you offer similar support for listening to Phoenix Channel from Erlang Node as well?

Thanks
Nitin

**Comment by sasa1977** [comment]
The`undef, [{'Elixir.GenServer',start_link` part at the beginning of an error seems to indicate that Elixir standard library is not included in the system. Unfortunately, as I said, I'm not familiar with the plugin, so I can't help you more at the moment. Time-permitting, I'll try to play with this on my own, and if I get somewhere, include a demo project, but I can't really say when/if this will happen.

**Comment by nitinjain1105** [comment]
Hi @sasa1977 

I tried following this link: https://www.rebar3.org/docs/using-available-plugins#section-elixir-dependencies
1- I added the plugins, hooks, overlay and modified vm.args
then I followed - https://www.rebar3.org/docs/releases#section-deployable
2- rebar3 release -d false
3- rebar3 as prod tar
4- mkdir myrel
5- mv myrel-0.1.0.tar.gz myrel/
6- cd myrel
7- tar -zxvf myrel-0.1.0.tar.gz
8- bin/myrel console

I still get undefined error. Any help would be much much appreciated. Hope to hear back from you.

**Comment by sasa1977** [comment]
I just quickly tried running an Elixir project with rebar3, and hit a few minor bumps, so here are some tips:

- You need to have Elixir 1.7.4 or higher installed and available in the path. Also install hex with `mix local.hex`
- Make sure to use the latest github version of the `rebar_mix` plugin (with `{rebar_mix, ".*",
     {git, "https://github.com/tsloughter/rebar_mix.git", {branch, "master"}}}`, I also had to remove the plugin to have the proper version reinstalled)
- Add `{pre,  [{compile, {mix, find_elixir_libs}}]}` to the `provider_hooks` list
- Include `elixir` under `applications` in your `app.src`

That got me to the point where Elixir is working in a local shell (I didn't try a release though). Unfortunately, I wasn't able to add `phoenix_gen_socket_client` as a dependency, because rebar3 complains:

```
===> Dep poison has invalid version ~> 2.0 or ~> 3.0
```

Which is caused by [this line in phoenix_gen_socket_client](https://github.com/Aircloak/phoenix_gen_socket_client/blob/master/mix.exs#L38). 

This dependency requirement is valid, but it seems that rebar3 doesn't support it.
So it looks like at this point the thing won't fly, but I didn't spend any more time looking into this, so I might be wrong. I suggest you turn to rebar3/rebar_mix related channels for further help.

**Comment by nitinjain1105** [comment]
Hi @sasa1977 

So I got the resolution for undef error I had earlier. I was not adding elixir/bin path to my erl -pa option.

I have just one last piece remaining:  I used to write my init function in Elixir like this -
  def init(url) do
    Agent.start_link(fn -> %{} end, name: Dispatcher.Agent)
    {:connect, url, [{"user_id", Atom.to_string(node())}], %{}}
  end

Cannot figure out how it would be for erlang. There are no agents in Erlang, so how should I go about that!!

**Comment by sasa1977** [comment]
If you're able to link everything properly, then you can still invoke Agent from your Erlang code by using `'Elixir.Agent':start_link(...)`. For more information about Erlang vs Elixir see [this page](https://elixir-lang.org/crash-course.html), in particular [this section](https://elixir-lang.org/crash-course.html#adding-elixir-to-existing-erlang-programs).

Also, for future reference, please don't use this project issue board for general purpose questions about Elixir or Erlang. Such questions do not belong here, and I advise asking them on dedicated community exchange sites, such as [Elixir forum](https://elixirforum.com/).
